server:
  port: 0

spring:
  application:
    name: user-service
  h2:
    console:
      enable: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: hello~

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
#token:
#  expiration_time: 8640000
#  secret: user_token